/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/gazebo2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useConfigurator } from '../contexts/Configurator';

export function Gazebo2(props) {
  const { nodes, materials } = useGLTF('./models/gazebo2.gltf')
  const { gcdOneTexture, gazeboCeilingDrapeOne, gazeboCeilingDrapeTwo, gazeboCeilingDrapeThree } = useConfigurator();

  return (
    <group {...props} dispose={null} scale={[0.01, 0.01, 0.01]} >


      {/* pillar hanging curtain  */}


      {/* {gcdOneTexture === "gcdOneTextureOne" && ( */}
      {gazeboCeilingDrapeOne === true && (
        <>
          {/* <group visible={false}> */}
          <group position={[-114.12, 46.03, -60.35]} rotation={[0, -0.81, 0]} scale={0.05}>
            <mesh geometry={nodes.Object002014.geometry} material={materials['Material #756.017']} position={[1503.59, 214.12, -1530.52]} rotation={[Math.PI, -0.38, Math.PI]} scale={[0.25, 0.49, 0.49]} visible={true} />
          </group>
          <mesh geometry={nodes.Object002.geometry} material={materials['Material #756']} position={[-57.88, 56.18, -117.55]} rotation={[0, 1.15, 0]} scale={[0.01, 0.02, 0.02]} />
          <mesh geometry={nodes.Object002004.geometry} material={materials['Material #756.004']} position={[-58.35, 56.77, -106.46]} rotation={[0, -1.19, 0]} scale={[0.01, 0.02, 0.02]} visible={true} />
          <mesh geometry={nodes.Object002005.geometry} material={materials['Material #756.005']} position={[-47.8, 56.33, -77.43]} rotation={[-Math.PI, 1.19, -Math.PI]} scale={[0.01, 0.02, 0.02]} visible={true} />
          <mesh geometry={nodes.Object002001.geometry} material={materials['Material #756.006']} position={[-47.92, 56.33, -147.22]} rotation={[Math.PI, -1.15, Math.PI]} scale={[0.01, 0.02, 0.02]} visible={true} />
          <mesh geometry={nodes.Object002007.geometry} material={materials['Material #756.010']} position={[28.34, 56.33, -155.12]} rotation={[-Math.PI, 0.45, -Math.PI]} scale={[0.01, 0.02, 0.02]} />
          <mesh geometry={nodes.Object002010.geometry} material={materials['Material #756.013']} position={[48.81, 56.47, -107.56]} rotation={[Math.PI, -1.14, Math.PI]} scale={[0.01, 0.02, 0.02]} />
          <mesh geometry={nodes.Object002011.geometry} material={materials['Material #756.014']} position={[37.84, 56.33, -78.06]} rotation={[0, 1.14, 0]} scale={[0.01, 0.02, 0.02]} />
          <mesh geometry={nodes.Object002012.geometry} material={materials['Material #756.015']} position={[1.22, 56.33, -58.6]} rotation={[0, 0.35, 0]} scale={[0.01, 0.02, 0.02]} />
          <mesh geometry={nodes.Object002013.geometry} material={materials['Material #756.016']} position={[29.87, 56.47, -71.64]} rotation={[Math.PI, -0.35, Math.PI]} scale={[0.01, 0.02, 0.02]} visible={true} />


        </>
      )};


      {/* </group> */}


      {/* cover curtain  */}

      {gazeboCeilingDrapeTwo === true && (
        <>

          {/* <group visible={false} > */}
          <mesh geometry={nodes.Plane002.geometry} material={materials['2K_Fabric01.001']} position={[15.81, 42.98, -65.59]} rotation={[0, 0.39, 0]} scale={[4.33, 3.33, 1.8]} />
          <mesh geometry={nodes.Plane003.geometry} material={materials['2K_Fabric01.002']} position={[41.77, 42.98, -94.1]} rotation={[0, 1.17, 0]} scale={[4.33, 3.33, 1.8]} />
          <mesh geometry={nodes.Plane004.geometry} material={materials['2K_Fabric01.003']} position={[41.15, 42.98, -131.76]} rotation={[-Math.PI, 1.21, -Math.PI]} scale={[4.33, 3.33, 1.8]} />
          <mesh geometry={nodes.Plane005.geometry} material={materials['2K_Fabric01.004']} position={[13.81, 42.98, -159.65]} rotation={[-Math.PI, 0.39, -Math.PI]} scale={[4.33, 3.33, 1.8]} />
          <mesh geometry={nodes.Plane007.geometry} material={materials['2K_Fabric01.006']} position={[-25.44, 42.98, -160.01]} rotation={[Math.PI, -0.39, Math.PI]} scale={[4.33, 3.33, 1.8]} />
          {/* </group> */}
        </>
      )};

      {/* white curtain */}


      {gazeboCeilingDrapeThree === true && (
        <>

          {/* <group visible={false}> */}

          <mesh geometry={nodes.Plane001.geometry} material={materials['2K_Fabric01.007']} position={[-25.73, 92.97, -161.07]} rotation={[2.93, -0.49, 2.32]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane008.geometry} material={materials['2K_Fabric01.008']} position={[-27.75, 92.41, -160.25]} rotation={[-0.2, 0.26, 2.54]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane009.geometry} material={materials['2K_Fabric01.009']} position={[-54.23, 92.41, -130.54]} rotation={[-0.39, 1.04, 2.83]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane010.geometry} material={materials['2K_Fabric01.010']} position={[-53.42, 92.97, -132.57]} rotation={[2.51, -1.25, 1.82]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane011.geometry} material={materials['2K_Fabric01.011']} position={[-53.48, 92.97, -91.78]} rotation={[0.39, -1.05, -0.37]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane012.geometry} material={materials['2K_Fabric01.012']} position={[-52.69, 92.41, -89.75]} rotation={[-2.48, 1.25, -1.29]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane013.geometry} material={materials['2K_Fabric01.013']} position={[-23.18, 92.41, -61.59]} rotation={[-2.91, 0.54, -0.78]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane014.geometry} material={materials['2K_Fabric01.014']} position={[-25.16, 92.97, -62.51]} rotation={[0.2, -0.31, -0.65]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane015.geometry} material={materials['2K_Fabric01.015']} position={[15.03, 92.97, -63.46]} rotation={[0.22, 0.52, -0.82]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane016.geometry} material={materials['2K_Fabric01.016']} position={[17.03, 92.41, -64.33]} rotation={[-2.94, -0.29, -0.6]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane017.geometry} material={materials['2K_Fabric01.017']} position={[44.78, 92.41, -93.9]} rotation={[-2.77, -1.01, -0.34]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane018.geometry} material={materials['2K_Fabric01.018']} position={[43.91, 92.97, -91.9]} rotation={[0.59, 1.22, -1.27]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane019.geometry} material={materials['2K_Fabric01.019']} position={[43.36, 92.97, -131.52]} rotation={[2.74, 1.06, 2.78]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane020.geometry} material={materials['2K_Fabric01.020']} position={[42.59, 92.41, -133.56]} rotation={[-0.68, -1.26, 1.82]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane021.geometry} material={materials['2K_Fabric01.021']} position={[12.89, 92.41, -161.28]} rotation={[-0.23, -0.52, 2.37]} scale={[3.15, 2.8, 2.16]} />
          <mesh geometry={nodes.Plane022.geometry} material={materials['2K_Fabric01.022']} position={[14.89, 92.97, -160.39]} rotation={[2.94, 0.3, 2.49]} scale={[-3.4, -3.02, -2.34]} />
          <mesh geometry={nodes.Plane023.geometry} material={materials['2K_Fabric01.023']} position={[47.32, 71.12, -114.95]} rotation={[-0.16, -1.3, 2.25]} scale={[6.32, 5.61, 4.34]} />
          <mesh geometry={nodes.Plane024.geometry} material={materials['2K_Fabric01.024']} position={[47.57, 71.06, -108.51]} rotation={[0.03, 1.2, -0.75]} scale={[-6.55, -5.81, -4.5]} />
          <mesh geometry={nodes.Plane025.geometry} material={materials['2K_Fabric01.025']} position={[-45.31, 71.06, -77.04]} rotation={[0.03, -1.17, -0.7]} scale={[-6.55, -5.81, -4.5]} />
          <mesh geometry={nodes.Plane026.geometry} material={materials['2K_Fabric01.026']} position={[-40.62, 71.12, -72.62]} rotation={[-3.09, 0.53, -0.76]} scale={[6.32, 5.61, 4.34]} />
          {/* </group> */}
        </>
      )};


      {/* white cloth ends */}


      {/* Base of gazebo  */}
      <mesh geometry={nodes.gazebo_base.geometry} material={materials['Material-Custom__3_']} position={[32.36, -55.21, -145.07]} visible={true} />

      {/* structure of gazebo  */}
      <mesh geometry={nodes.gazebo_colonne_Cilindro2001.geometry} material={materials['Material-Custom__2_']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro2002.geometry} material={materials['Material-Custom__1_']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro001.geometry} material={materials['Material-Custom__1_.001']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro002.geometry} material={materials['Material-Custom__2_.001']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro003.geometry} material={materials['Material-Custom__1_.002']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro1001.geometry} material={materials['Material-Custom__1_.003']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro1002.geometry} material={materials['Material-Custom__2_.002']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro1003.geometry} material={materials['Material-Custom__1_.004']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro4001.geometry} material={materials['Material-Custom__1_.005']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro4002.geometry} material={materials['Material-Custom__2_.003']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro4003.geometry} material={materials['Material-Custom__1_.006']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro5001.geometry} material={materials['Material-Custom__1_.007']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro5002.geometry} material={materials['Material-Custom__2_.004']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro5003.geometry} material={materials['Material-Custom__1_.008']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro6001.geometry} material={materials['Material-Custom__1_.009']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro6002.geometry} material={materials['Material-Custom__2_.005']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro6003.geometry} material={materials['Material-Custom__1_.010']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro7001.geometry} material={materials['Material-Custom__1_.011']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro7002.geometry} material={materials['Material-Custom__2_.006']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro7003.geometry} material={materials['Material-Custom__1_.012']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro8001.geometry} material={materials['Material-Custom__1_.013']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro8002.geometry} material={materials['Material-Custom__2_.007']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro8003.geometry} material={materials['Material-Custom__1_.014']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro2003.geometry} material={materials['Material-Custom__1_.015']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro2004.geometry} material={materials['a0000000-0000-0000-0000-000000000000.003']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_colonne_Cilindro2005.geometry} material={materials['a0000000-0000-0000-0000-000000000000.003']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3032.geometry} material={materials['Material-Custom.001']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3033.geometry} material={materials['Material-Custom.002']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3036.geometry} material={materials['Material-Custom.005']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3040.geometry} material={materials['Material-Custom.009']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3041.geometry} material={materials['Material-Custom.010']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3042.geometry} material={materials['Material-Custom.011']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3043.geometry} material={materials['Material-Custom.012']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3044.geometry} material={materials['Material-Custom.013']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3045.geometry} material={materials['Material-Custom.014']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3047.geometry} material={materials['Material-Custom.016']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3048.geometry} material={materials['Material-Custom.017']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3049.geometry} material={materials['Material-Custom.018']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3050.geometry} material={materials['Material-Custom.019']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3051.geometry} material={materials['Material-Custom.020']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3052.geometry} material={materials['Material-Custom.021']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3053.geometry} material={materials['Material-Custom.022']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3054.geometry} material={materials['Material-Custom.023']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3055.geometry} material={materials['Material-Custom.024']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3056.geometry} material={materials['Material-Custom.025']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3057.geometry} material={materials['Material-Custom.026']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3058.geometry} material={materials['Material-Custom.027']} position={[32.36, -55.21, -145.07]} />
      <mesh geometry={nodes.gazebo_Cilindro3007.geometry} material={materials['a0000000-0000-0000-0000-000000000000']} />


    </group>
  )
}

useGLTF.preload('./models/gazebo2.gltf')
