/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/gazebo/gfsl.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useAnimations } from '@react-three/drei';
import { useConfigurator } from '../contexts/Configurator';

import * as THREE from "three";

export function Gfsl(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/gazebo/gfsl.gltf')
  const { actions } = useAnimations(animations, group);

  const { gazeboSeatOne, gazeboSeatTwo, gazeboSeatThree } = useConfigurator();

  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Scene">

        {gazeboSeatOne === true && (
          <>

            <group name="Couch1" position={[-13.34, -0.87, -11.01]} rotation={[Math.PI / 2, 0, 1.99]} scale={0.01} visible={true}>
              <mesh name="Couch1_1" geometry={nodes.Couch1_1.geometry} material={materials.Custom} />
              <mesh name="Couch1_2" geometry={nodes.Couch1_2.geometry} material={materials['Custom (1)']} />
              <mesh name="Couch1_3" geometry={nodes.Couch1_3.geometry} material={materials.wire_115115115} />
              <mesh name="Couch1_4" geometry={nodes.Couch1_4.geometry} material={materials['Custom (2)']} />
            </group>

          </>
        )}

        {gazeboSeatTwo === true && (
          <>


            <group name="Couch2" position={[-13.3, -0.84, -11]} rotation={[Math.PI / 2, 0, 1.99]} scale={0.01} visible={true} >
              <mesh name="Couch2_1" geometry={nodes.Couch2_1.geometry} material={materials['Custom (2).001']} />
              <mesh name="Couch2_2" geometry={nodes.Couch2_2.geometry} material={materials['Custom (1).001']} />
              <mesh name="Couch2_3" geometry={nodes.Couch2_3.geometry} material={materials['wire_115115115.001']} />
              <mesh name="Couch2_4" geometry={nodes.Couch2_4.geometry} material={materials['Custom.001']} />
            </group>
          </>
        )}

        {gazeboSeatThree === true && (
          <>

            <group name='chairs' visible={true} >
              <group name="chair_1" position={[-13.12, -1.59, -7.99]} rotation={[Math.PI / 2, 0, 0.42]} scale={0.39} visible={true} >
                <mesh name="chair_1_1" geometry={nodes.chair_1_1.geometry} material={materials.drop_result} />
                <mesh name="chair_1_2" geometry={nodes.chair_1_2.geometry} material={materials.Translucent_Glass_Sky_Reflection} />
                <mesh name="chair_1_3" geometry={nodes.chair_1_3.geometry} material={materials.Wood_Cherry_Original} />
              </group>

              <group name="chair_1001" position={[-11.73, -1.59, -7.36]} rotation={[Math.PI / 2, 0, 0.42]} scale={0.39} visible={true} >
                <mesh name="chair_1001_1" geometry={nodes.chair_1001_1.geometry} material={materials['drop_result.001']} />
                <mesh name="chair_1001_2" geometry={nodes.chair_1001_2.geometry} material={materials['Translucent_Glass_Sky_Reflection.001']} />
                <mesh name="chair_1001_3" geometry={nodes.chair_1001_3.geometry} material={materials['Wood_Cherry_Original.001']} />
              </group>

              <group name="chair_1002" position={[-11.41, -1.59, -12.02]} rotation={[Math.PI / 2, 0, 0.42]} scale={0.39} visible={true}>
                <mesh name="chair_1002_1" geometry={nodes.chair_1002_1.geometry} material={materials['drop_result.002']} />
                <mesh name="chair_1002_2" geometry={nodes.chair_1002_2.geometry} material={materials['Translucent_Glass_Sky_Reflection.002']} />
                <mesh name="chair_1002_3" geometry={nodes.chair_1002_3.geometry} material={materials['Wood_Cherry_Original.002']} />
              </group>

              <group name="chair_1003" position={[-10.13, -1.59, -11.47]} rotation={[Math.PI / 2, 0, 0.42]} scale={0.39} visible={true} >
                <mesh name="chair_1003_1" geometry={nodes.chair_1003_1.geometry} material={materials['drop_result.003']} />
                <mesh name="chair_1003_2" geometry={nodes.chair_1003_2.geometry} material={materials['Translucent_Glass_Sky_Reflection.003']} />
                <mesh name="chair_1003_3" geometry={nodes.chair_1003_3.geometry} material={materials['Wood_Cherry_Original.003']} />
              </group>

            </group>

          </>
        )}


      </group>
    </group>
  )
}

useGLTF.preload('./models/gazebo/gfsl.gltf')
