/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/gazebo/gpd.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useAnimations } from '@react-three/drei';
import { useConfigurator } from '../contexts/Configurator';

import * as THREE from "three";

export function Gpd(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/gazebo/gpd.gltf')
  const { actions } = useAnimations(animations, group);

  const { gpdOneTexture, gpdTwoTexture, gpdThreeTexture, gazeboPillarDrapeOne, gazeboPillarDrapeTwo, gazeboPillarDrapeThree } = useConfigurator();


  const materialTextureProps = useTexture({
    map: './gcdTextures/texOne/grey.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texOne/grey.jpg',
    roughnessMap: './gcdTextures/texOne/grey.jpg',
    aoMap: './gcdTextures/texOne/grey.jpg',
  })

  materialTextureProps.map.repeat.set(3, 3);
  materialTextureProps.normalMap.repeat.set(3, 3);
  materialTextureProps.roughnessMap.repeat.set(3, 3);
  materialTextureProps.aoMap.repeat.set(3, 3);

  materialTextureProps.map.wrapS =
    materialTextureProps.map.wrapT =
    materialTextureProps.normalMap.wrapS =
    materialTextureProps.normalMap.wrapT =
    materialTextureProps.roughnessMap.wrapS =
    materialTextureProps.roughnessMap.wrapT =
    materialTextureProps.aoMap.wrapS =
    materialTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const gcdRedTextureProps = useTexture({
    map: './gcdTextures/texTwo/red.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texTwo/red.jpg',
    roughnessMap: './gcdTextures/texTwo/red.jpg',
    aoMap: './gcdTextures/texTwo/red.jpg',
  })

  gcdRedTextureProps.map.repeat.set(3, 3);
  gcdRedTextureProps.normalMap.repeat.set(3, 3);
  gcdRedTextureProps.roughnessMap.repeat.set(3, 3);
  gcdRedTextureProps.aoMap.repeat.set(3, 3);

  gcdRedTextureProps.map.wrapS =
    gcdRedTextureProps.map.wrapT =
    gcdRedTextureProps.normalMap.wrapS =
    gcdRedTextureProps.normalMap.wrapT =
    gcdRedTextureProps.roughnessMap.wrapS =
    gcdRedTextureProps.roughnessMap.wrapT =
    gcdRedTextureProps.aoMap.wrapS =
    gcdRedTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const gcdYellowTextureProps = useTexture({
    map: './gcdTextures/texThree/yellow.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texThree/yellow.jpg',
    roughnessMap: './gcdTextures/texThree/yellow.jpg',
    aoMap: './gcdTextures/texThree/yellow.jpg',
  })

  gcdYellowTextureProps.map.repeat.set(3, 3);
  gcdYellowTextureProps.normalMap.repeat.set(3, 3);
  gcdYellowTextureProps.roughnessMap.repeat.set(3, 3);
  gcdYellowTextureProps.aoMap.repeat.set(3, 3);

  gcdYellowTextureProps.map.wrapS =
    gcdYellowTextureProps.map.wrapT =
    gcdYellowTextureProps.normalMap.wrapS =
    gcdYellowTextureProps.normalMap.wrapT =
    gcdYellowTextureProps.roughnessMap.wrapS =
    gcdYellowTextureProps.roughnessMap.wrapT =
    gcdYellowTextureProps.aoMap.wrapS =
    gcdYellowTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;

  const fourTextureProps = useTexture({
    map: './gcdTextures/texFour/cream.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texFour/cream.jpg',
    roughnessMap: './gcdTextures/texFour/cream.jpg',
    aoMap: './gcdTextures/texFour/cream.jpg',
  })

  fourTextureProps.map.repeat.set(3, 3);
  fourTextureProps.normalMap.repeat.set(3, 3);
  fourTextureProps.roughnessMap.repeat.set(3, 3);
  fourTextureProps.aoMap.repeat.set(3, 3);

  fourTextureProps.map.wrapS =
    fourTextureProps.map.wrapT =
    fourTextureProps.normalMap.wrapS =
    fourTextureProps.normalMap.wrapT =
    fourTextureProps.roughnessMap.wrapS =
    fourTextureProps.roughnessMap.wrapT =
    fourTextureProps.aoMap.wrapS =
    fourTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;

  const fiveTextureProps = useTexture({
    map: './gcdTextures/texFive/translucent.png',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texFive/translucent.png',
    roughnessMap: './gcdTextures/texFive/translucent.png',
    aoMap: './gcdTextures/texFive/translucent.png',
  })

  fiveTextureProps.map.repeat.set(3, 3);
  fiveTextureProps.normalMap.repeat.set(3, 3);
  fiveTextureProps.roughnessMap.repeat.set(3, 3);
  fiveTextureProps.aoMap.repeat.set(3, 3);

  fiveTextureProps.map.wrapS =
    fiveTextureProps.map.wrapT =
    fiveTextureProps.normalMap.wrapS =
    fiveTextureProps.normalMap.wrapT =
    fiveTextureProps.roughnessMap.wrapS =
    fiveTextureProps.roughnessMap.wrapT =
    fiveTextureProps.aoMap.wrapS =
    fiveTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const sixTextureProps = useTexture({
    map: './gcdTextures/texSix/lightGreen.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texSix/lightGreen.jpg',
    roughnessMap: './gcdTextures/texSix/lightGreen.jpg',
    aoMap: './gcdTextures/texSix/lightGreen.jpg',
  })

  sixTextureProps.map.repeat.set(3, 3);
  sixTextureProps.normalMap.repeat.set(3, 3);
  sixTextureProps.roughnessMap.repeat.set(3, 3);
  sixTextureProps.aoMap.repeat.set(3, 3);

  sixTextureProps.map.wrapS =
    sixTextureProps.map.wrapT =
    sixTextureProps.normalMap.wrapS =
    sixTextureProps.normalMap.wrapT =
    sixTextureProps.roughnessMap.wrapS =
    sixTextureProps.roughnessMap.wrapT =
    sixTextureProps.aoMap.wrapS =
    sixTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const sevenTextureProps = useTexture({
    map: './gcdTextures/texSeven/orange.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texSeven/orange.jpg',
    roughnessMap: './gcdTextures/texSeven/orange.jpg',
    aoMap: './gcdTextures/texSeven/orange.jpg',
  })

  sevenTextureProps.map.repeat.set(3, 3);
  sevenTextureProps.normalMap.repeat.set(3, 3);
  sevenTextureProps.roughnessMap.repeat.set(3, 3);
  sevenTextureProps.aoMap.repeat.set(3, 3);

  sevenTextureProps.map.wrapS =
    sevenTextureProps.map.wrapT =
    sevenTextureProps.normalMap.wrapS =
    sevenTextureProps.normalMap.wrapT =
    sevenTextureProps.roughnessMap.wrapS =
    sevenTextureProps.roughnessMap.wrapT =
    sevenTextureProps.aoMap.wrapS =
    sevenTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const eightTextureProps = useTexture({
    map: './gcdTextures/texEight/lightPink.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texEight/lightPink.jpg',
    roughnessMap: './gcdTextures/texEight/lightPink.jpg',
    aoMap: './gcdTextures/texEight/lightPink.jpg',
  })

  eightTextureProps.map.repeat.set(3, 3);
  eightTextureProps.normalMap.repeat.set(3, 3);
  eightTextureProps.roughnessMap.repeat.set(3, 3);
  eightTextureProps.aoMap.repeat.set(3, 3);

  eightTextureProps.map.wrapS =
    eightTextureProps.map.wrapT =
    eightTextureProps.normalMap.wrapS =
    eightTextureProps.normalMap.wrapT =
    eightTextureProps.roughnessMap.wrapS =
    eightTextureProps.roughnessMap.wrapT =
    eightTextureProps.aoMap.wrapS =
    eightTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;




  const nineTextureProps = useTexture({
    map: './gcdTextures/texNine/lightVelvet.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texNine/lightVelvet.jpg',
    roughnessMap: './gcdTextures/texNine/lightVelvet.jpg',
    aoMap: './gcdTextures/texNine/lightVelvet.jpg',
  })

  nineTextureProps.map.repeat.set(3, 3);
  nineTextureProps.normalMap.repeat.set(3, 3);
  nineTextureProps.roughnessMap.repeat.set(3, 3);
  nineTextureProps.aoMap.repeat.set(3, 3);

  nineTextureProps.map.wrapS =
    nineTextureProps.map.wrapT =
    nineTextureProps.normalMap.wrapS =
    nineTextureProps.normalMap.wrapT =
    nineTextureProps.roughnessMap.wrapS =
    nineTextureProps.roughnessMap.wrapT =
    nineTextureProps.aoMap.wrapS =
    nineTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;



  const tenTextureProps = useTexture({
    map: './gcdTextures/texTen/blue.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texTen/blue.jpg',
    roughnessMap: './gcdTextures/texTen/blue.jpg',
    aoMap: './gcdTextures/texTen/blue.jpg',
  })

  tenTextureProps.map.repeat.set(3, 3);
  tenTextureProps.normalMap.repeat.set(3, 3);
  tenTextureProps.roughnessMap.repeat.set(3, 3);
  tenTextureProps.aoMap.repeat.set(3, 3);

  tenTextureProps.map.wrapS =
    tenTextureProps.map.wrapT =
    tenTextureProps.normalMap.wrapS =
    tenTextureProps.normalMap.wrapT =
    tenTextureProps.roughnessMap.wrapS =
    tenTextureProps.roughnessMap.wrapT =
    tenTextureProps.aoMap.wrapS =
    tenTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  return (
    <group ref={group} {...props} dispose={null} scale={[0.3, 0.3, 0.3]} >
      <group name="Scene" >

        {gazeboPillarDrapeOne === true && (
          <>
            <group name='scene2' visible={true} >
              <group name="gpd1" position={[-8.8, -1.54, -7.73]} rotation={[Math.PI / 2, 0, -0.83]} scale={0.54} visible={true}>
                <mesh name="gpd1_1" geometry={nodes.gpd1_1.geometry} material={materials.curtainnn} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1_2" geometry={nodes.gpd1_2.geometry} material={materials.da} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

              <group name="gpd1001" position={[-7.97, -1.54, -9.63]} rotation={[Math.PI / 2, 0, -1.26]} scale={0.54}>
                <mesh name="gpd1001_1" geometry={nodes.gpd1001_1.geometry} material={materials['curtainnn.001']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1001_2" geometry={nodes.gpd1001_2.geometry} material={materials['da.001']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1002" position={[-8.18, -1.54, -11.65]} rotation={[Math.PI / 2, 0, -1.84]} scale={0.54}>
                <mesh name="gpd1002_1" geometry={nodes.gpd1002_1.geometry} material={materials['curtainnn.002']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1002_2" geometry={nodes.gpd1002_2.geometry} material={materials['da.002']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1003" position={[-9.32, -1.54, -13.25]} rotation={[Math.PI / 2, 0, -2.37]} scale={0.54}>
                <mesh name="gpd1003_1" geometry={nodes.gpd1003_1.geometry} material={materials['curtainnn.003']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1003_2" geometry={nodes.gpd1003_2.geometry} material={materials['da.003']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1004" position={[-11.18, -1.54, -14.1]} rotation={[Math.PI / 2, 0, -2.89]} scale={0.54}>
                <mesh name="gpd1004_1" geometry={nodes.gpd1004_1.geometry} material={materials['curtainnn.004']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1004_2" geometry={nodes.gpd1004_2.geometry} material={materials['da.004']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1005" position={[-13.21, -1.54, -13.95]} rotation={[Math.PI / 2, 0, 2.84]} scale={0.54}>
                <mesh name="gpd1005_1" geometry={nodes.gpd1005_1.geometry} material={materials['curtainnn.005']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1005_2" geometry={nodes.gpd1005_2.geometry} material={materials['da.005']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1006" position={[-14.9, -1.54, -12.78]} rotation={[Math.PI / 2, 0, 2.34]} scale={0.54}>
                <mesh name="gpd1006_1" geometry={nodes.gpd1006_1.geometry} material={materials['curtainnn.006']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1006_2" geometry={nodes.gpd1006_2.geometry} material={materials['da.006']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1007" position={[-15.78, -1.54, -10.94]} rotation={[Math.PI / 2, 0, 1.78]} scale={0.54}>
                <mesh name="gpd1007_1" geometry={nodes.gpd1007_1.geometry} material={materials['curtainnn.007']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1007_2" geometry={nodes.gpd1007_2.geometry} material={materials['da.007']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1008" position={[-15.62, -1.54, -8.86]} rotation={[Math.PI / 2, 0, 1.29]} scale={0.54}>
                <mesh name="gpd1008_1" geometry={nodes.gpd1008_1.geometry} material={materials['curtainnn.008']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1008_2" geometry={nodes.gpd1008_2.geometry} material={materials['da.008']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1009" position={[-14.48, -1.54, -7.17]} rotation={[Math.PI / 2, 0, 0.74]} scale={0.54}>
                <mesh name="gpd1009_1" geometry={nodes.gpd1009_1.geometry} material={materials['curtainnn.009']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1009_2" geometry={nodes.gpd1009_2.geometry} material={materials['da.009']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

              <group name="gpd1010" position={[-12.59, -1.54, -6.31]} rotation={[Math.PI / 2, 0, 0.22]} scale={0.54}>
                <mesh name="gpd1010_1" geometry={nodes.gpd1010_1.geometry} material={materials['curtainnn.010']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1010_2" geometry={nodes.gpd1010_2.geometry} material={materials['da.010']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

              <group name="gpd1011" position={[-10.52, -1.54, -6.46]} rotation={[Math.PI / 2, 0, -0.36]} scale={0.54}>
                <mesh name="gpd1011_1" geometry={nodes.gpd1011_1.geometry} material={materials['curtainnn.011']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1011_2" geometry={nodes.gpd1011_2.geometry} material={materials['da.011']} >
                  <meshStandardMaterial {...gpdOneTexture === 0 ? materialTextureProps
                    : gpdOneTexture === 1 ? gcdRedTextureProps
                      : gpdOneTexture === 2 ? gcdYellowTextureProps
                        : gpdOneTexture === 3 ? fourTextureProps
                          : gpdOneTexture === 4 ? fiveTextureProps
                            : gpdOneTexture === 5 ? sixTextureProps
                              : gpdOneTexture === 6 ? sevenTextureProps
                                : gpdOneTexture === 7 ? eightTextureProps
                                  : gpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

            </group>
          </>
        )}


        {gazeboPillarDrapeTwo === true && (
          <>

            <group name='scene3' visible={true} >

              <group name="gpd1025" position={[-8.86, -0.14, -7.72]} rotation={[Math.PI / 2, 0, -0.92]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1025_1" geometry={nodes.gpd1025_1.geometry} material={materials['curtainnn.025']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1025_2" geometry={nodes.gpd1025_2.geometry} material={materials['da.025']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1026" position={[-8.02, -0.14, -9.51]} rotation={[Math.PI / 2, 0, -1.29]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1026_1" geometry={nodes.gpd1026_1.geometry} material={materials['curtainnn.026']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1026_2" geometry={nodes.gpd1026_2.geometry} material={materials['da.026']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1027" position={[-8.18, -0.14, -11.55]} rotation={[Math.PI / 2, 0, -1.8]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1027_1" geometry={nodes.gpd1027_1.geometry} material={materials['curtainnn.027']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1027_2" geometry={nodes.gpd1027_2.geometry} material={materials['da.027']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1028" position={[-9.36, -0.14, -13.23]} rotation={[Math.PI / 2, 0, -2.44]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1028_1" geometry={nodes.gpd1028_1.geometry} material={materials['curtainnn.028']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1028_2" geometry={nodes.gpd1028_2.geometry} material={materials['da.028']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1029" position={[-11.1, -0.14, -14.14]} rotation={[Math.PI / 2, 0, -2.95]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1029_1" geometry={nodes.gpd1029_1.geometry} material={materials['curtainnn.029']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1029_2" geometry={nodes.gpd1029_2.geometry} material={materials['da.029']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

              <group name="gpd1030" position={[-13.22, -0.14, -13.97]} rotation={[Math.PI / 2, 0, 2.79]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1030_1" geometry={nodes.gpd1030_1.geometry} material={materials['curtainnn.030']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1030_2" geometry={nodes.gpd1030_2.geometry} material={materials['da.030']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1031" position={[-15, -0.14, -12.82]} rotation={[Math.PI / 2, 0, 2.31]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1031_1" geometry={nodes.gpd1031_1.geometry} material={materials['curtainnn.031']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1031_2" geometry={nodes.gpd1031_2.geometry} material={materials['da.031']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1032" position={[-15.78, -0.14, -10.97]} rotation={[Math.PI / 2, 0, 1.75]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1032_1" geometry={nodes.gpd1032_1.geometry} material={materials['curtainnn.032']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1032_2" geometry={nodes.gpd1032_2.geometry} material={materials['da.032']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1033" position={[-15.57, -0.14, -8.94]} rotation={[Math.PI / 2, 0, 1.23]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1033_1" geometry={nodes.gpd1033_1.geometry} material={materials['curtainnn.033']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1033_2" geometry={nodes.gpd1033_2.geometry} material={materials['da.033']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1034" position={[-14.46, -0.14, -7.25]} rotation={[Math.PI / 2, 0, 0.75]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1034_1" geometry={nodes.gpd1034_1.geometry} material={materials['curtainnn.034']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1034_2" geometry={nodes.gpd1034_2.geometry} material={materials['da.034']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1035" position={[-12.6, -0.14, -6.33]} rotation={[Math.PI / 2, 0, 0.19]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1035_1" geometry={nodes.gpd1035_1.geometry} material={materials['curtainnn.035']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1035_2" geometry={nodes.gpd1035_2.geometry} material={materials['da.035']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1036" position={[-10.54, -0.14, -6.5]} rotation={[Math.PI / 2, 0, -0.35]} scale={[0.71, 0.65, 0.91]}>
                <mesh name="gpd1036_1" geometry={nodes.gpd1036_1.geometry} material={materials['curtainnn.036']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1036_2" geometry={nodes.gpd1036_2.geometry} material={materials['da.036']} >
                  <meshStandardMaterial {...gpdTwoTexture === 0 ? materialTextureProps
                    : gpdTwoTexture === 1 ? gcdRedTextureProps
                      : gpdTwoTexture === 2 ? gcdYellowTextureProps
                        : gpdTwoTexture === 3 ? fourTextureProps
                          : gpdTwoTexture === 4 ? fiveTextureProps
                            : gpdTwoTexture === 5 ? sixTextureProps
                              : gpdTwoTexture === 6 ? sevenTextureProps
                                : gpdTwoTexture === 7 ? eightTextureProps
                                  : gpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

            </group>
          </>
        )}


        {gazeboPillarDrapeThree === true && (
          <>

            <group name='scene2' visible={true} >
              <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['2K_Fabric01.075']} position={[-8.32, 2.51, -8.51]} rotation={[0.08, 1.17, -0.78]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['2K_Fabric01.076']} position={[-8.26, 2.49, -8.61]} rotation={[-3.07, -0.94, -0.65]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['2K_Fabric01.087']} position={[-7.87, 2.51, -10.55]} rotation={[2.81, 1.38, 2.74]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['2K_Fabric01.088']} position={[-7.88, 2.48, -10.67]} rotation={[-2.2, -1.49, 0.26]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['2K_Fabric01.089']} position={[-8.68, 2.48, -12.59]} rotation={[-0.14, -1.08, 2.33]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['2K_Fabric01.090']} position={[-8.62, 2.51, -12.49]} rotation={[3.05, 0.85, 2.49]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['2K_Fabric01.091']} position={[-9.61, 2.51, -6.95]} rotation={[0.08, 0.72, -0.77]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['2K_Fabric01.092']} position={[-9.51, 2.48, -7.01]} rotation={[-3.07, -0.49, -0.65]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['2K_Fabric01.093']} position={[-11.47, 2.48, -6.24]} rotation={[-3.07, 0.05, -0.69]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['2K_Fabric01.094']} position={[-11.59, 2.51, -6.24]} rotation={[0.06, 0.17, -0.73]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['2K_Fabric01.095']} position={[-13.64, 2.51, -6.62]} rotation={[0.06, -0.35, -0.7]} scale={[-0.18, -0.16, -0.13]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>
              <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['2K_Fabric01.096']} position={[-13.53, 2.48, -6.56]} rotation={[-3.06, 0.57, -0.73]} scale={[0.17, 0.15, 0.12]} >
                <meshStandardMaterial {...gpdThreeTexture === 0 ? materialTextureProps
                  : gpdThreeTexture === 1 ? gcdRedTextureProps
                    : gpdThreeTexture === 2 ? gcdYellowTextureProps
                      : gpdThreeTexture === 3 ? fourTextureProps
                        : gpdThreeTexture === 4 ? fiveTextureProps
                          : gpdThreeTexture === 5 ? sixTextureProps
                            : gpdThreeTexture === 6 ? sevenTextureProps
                              : gpdThreeTexture === 7 ? eightTextureProps
                                : gpdThreeTexture === 8 ? nineTextureProps
                                  : tenTextureProps} />
              </mesh>

            </group>
          </>
        )}
      </group>
    </group >
  )
}

useGLTF.preload('./models/gazebo/gpd.gltf')
