/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/lawn/lpd.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useAnimations } from '@react-three/drei';
import { useConfigurator } from '../contexts/Configurator';

import * as THREE from "three";

export function Lpd(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/lawn/lpd.gltf')
  const { actions } = useAnimations(animations, group);

  const { lpdOneTexture, lpdTwoTexture, lawnPillarDrapeOne, lawnPillarDrapeTwo } = useConfigurator();



  const materialTextureProps = useTexture({
    map: './gcdTextures/texOne/grey.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texOne/grey.jpg',
    roughnessMap: './gcdTextures/texOne/grey.jpg',
    aoMap: './gcdTextures/texOne/grey.jpg',
  })

  materialTextureProps.map.repeat.set(3, 3);
  materialTextureProps.normalMap.repeat.set(3, 3);
  materialTextureProps.roughnessMap.repeat.set(3, 3);
  materialTextureProps.aoMap.repeat.set(3, 3);

  materialTextureProps.map.wrapS =
    materialTextureProps.map.wrapT =
    materialTextureProps.normalMap.wrapS =
    materialTextureProps.normalMap.wrapT =
    materialTextureProps.roughnessMap.wrapS =
    materialTextureProps.roughnessMap.wrapT =
    materialTextureProps.aoMap.wrapS =
    materialTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const gcdRedTextureProps = useTexture({
    map: './gcdTextures/texTwo/red.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texTwo/red.jpg',
    roughnessMap: './gcdTextures/texTwo/red.jpg',
    aoMap: './gcdTextures/texTwo/red.jpg',
  })

  gcdRedTextureProps.map.repeat.set(3, 3);
  gcdRedTextureProps.normalMap.repeat.set(3, 3);
  gcdRedTextureProps.roughnessMap.repeat.set(3, 3);
  gcdRedTextureProps.aoMap.repeat.set(3, 3);

  gcdRedTextureProps.map.wrapS =
    gcdRedTextureProps.map.wrapT =
    gcdRedTextureProps.normalMap.wrapS =
    gcdRedTextureProps.normalMap.wrapT =
    gcdRedTextureProps.roughnessMap.wrapS =
    gcdRedTextureProps.roughnessMap.wrapT =
    gcdRedTextureProps.aoMap.wrapS =
    gcdRedTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const gcdYellowTextureProps = useTexture({
    map: './gcdTextures/texThree/yellow.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texThree/yellow.jpg',
    roughnessMap: './gcdTextures/texThree/yellow.jpg',
    aoMap: './gcdTextures/texThree/yellow.jpg',
  })

  gcdYellowTextureProps.map.repeat.set(3, 3);
  gcdYellowTextureProps.normalMap.repeat.set(3, 3);
  gcdYellowTextureProps.roughnessMap.repeat.set(3, 3);
  gcdYellowTextureProps.aoMap.repeat.set(3, 3);

  gcdYellowTextureProps.map.wrapS =
    gcdYellowTextureProps.map.wrapT =
    gcdYellowTextureProps.normalMap.wrapS =
    gcdYellowTextureProps.normalMap.wrapT =
    gcdYellowTextureProps.roughnessMap.wrapS =
    gcdYellowTextureProps.roughnessMap.wrapT =
    gcdYellowTextureProps.aoMap.wrapS =
    gcdYellowTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;

  const fourTextureProps = useTexture({
    map: './gcdTextures/texFour/cream.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texFour/cream.jpg',
    roughnessMap: './gcdTextures/texFour/cream.jpg',
    aoMap: './gcdTextures/texFour/cream.jpg',
  })

  fourTextureProps.map.repeat.set(3, 3);
  fourTextureProps.normalMap.repeat.set(3, 3);
  fourTextureProps.roughnessMap.repeat.set(3, 3);
  fourTextureProps.aoMap.repeat.set(3, 3);

  fourTextureProps.map.wrapS =
    fourTextureProps.map.wrapT =
    fourTextureProps.normalMap.wrapS =
    fourTextureProps.normalMap.wrapT =
    fourTextureProps.roughnessMap.wrapS =
    fourTextureProps.roughnessMap.wrapT =
    fourTextureProps.aoMap.wrapS =
    fourTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;

  const fiveTextureProps = useTexture({
    map: './gcdTextures/texFive/translucent.png',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texFive/translucent.png',
    roughnessMap: './gcdTextures/texFive/translucent.png',
    aoMap: './gcdTextures/texFive/translucent.png',
  })

  fiveTextureProps.map.repeat.set(3, 3);
  fiveTextureProps.normalMap.repeat.set(3, 3);
  fiveTextureProps.roughnessMap.repeat.set(3, 3);
  fiveTextureProps.aoMap.repeat.set(3, 3);

  fiveTextureProps.map.wrapS =
    fiveTextureProps.map.wrapT =
    fiveTextureProps.normalMap.wrapS =
    fiveTextureProps.normalMap.wrapT =
    fiveTextureProps.roughnessMap.wrapS =
    fiveTextureProps.roughnessMap.wrapT =
    fiveTextureProps.aoMap.wrapS =
    fiveTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const sixTextureProps = useTexture({
    map: './gcdTextures/texSix/lightGreen.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texSix/lightGreen.jpg',
    roughnessMap: './gcdTextures/texSix/lightGreen.jpg',
    aoMap: './gcdTextures/texSix/lightGreen.jpg',
  })

  sixTextureProps.map.repeat.set(3, 3);
  sixTextureProps.normalMap.repeat.set(3, 3);
  sixTextureProps.roughnessMap.repeat.set(3, 3);
  sixTextureProps.aoMap.repeat.set(3, 3);

  sixTextureProps.map.wrapS =
    sixTextureProps.map.wrapT =
    sixTextureProps.normalMap.wrapS =
    sixTextureProps.normalMap.wrapT =
    sixTextureProps.roughnessMap.wrapS =
    sixTextureProps.roughnessMap.wrapT =
    sixTextureProps.aoMap.wrapS =
    sixTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const sevenTextureProps = useTexture({
    map: './gcdTextures/texSeven/orange.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texSeven/orange.jpg',
    roughnessMap: './gcdTextures/texSeven/orange.jpg',
    aoMap: './gcdTextures/texSeven/orange.jpg',
  })

  sevenTextureProps.map.repeat.set(3, 3);
  sevenTextureProps.normalMap.repeat.set(3, 3);
  sevenTextureProps.roughnessMap.repeat.set(3, 3);
  sevenTextureProps.aoMap.repeat.set(3, 3);

  sevenTextureProps.map.wrapS =
    sevenTextureProps.map.wrapT =
    sevenTextureProps.normalMap.wrapS =
    sevenTextureProps.normalMap.wrapT =
    sevenTextureProps.roughnessMap.wrapS =
    sevenTextureProps.roughnessMap.wrapT =
    sevenTextureProps.aoMap.wrapS =
    sevenTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  const eightTextureProps = useTexture({
    map: './gcdTextures/texEight/lightPink.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texEight/lightPink.jpg',
    roughnessMap: './gcdTextures/texEight/lightPink.jpg',
    aoMap: './gcdTextures/texEight/lightPink.jpg',
  })

  eightTextureProps.map.repeat.set(3, 3);
  eightTextureProps.normalMap.repeat.set(3, 3);
  eightTextureProps.roughnessMap.repeat.set(3, 3);
  eightTextureProps.aoMap.repeat.set(3, 3);

  eightTextureProps.map.wrapS =
    eightTextureProps.map.wrapT =
    eightTextureProps.normalMap.wrapS =
    eightTextureProps.normalMap.wrapT =
    eightTextureProps.roughnessMap.wrapS =
    eightTextureProps.roughnessMap.wrapT =
    eightTextureProps.aoMap.wrapS =
    eightTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;




  const nineTextureProps = useTexture({
    map: './gcdTextures/texNine/lightVelvet.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texNine/lightVelvet.jpg',
    roughnessMap: './gcdTextures/texNine/lightVelvet.jpg',
    aoMap: './gcdTextures/texNine/lightVelvet.jpg',
  })

  nineTextureProps.map.repeat.set(3, 3);
  nineTextureProps.normalMap.repeat.set(3, 3);
  nineTextureProps.roughnessMap.repeat.set(3, 3);
  nineTextureProps.aoMap.repeat.set(3, 3);

  nineTextureProps.map.wrapS =
    nineTextureProps.map.wrapT =
    nineTextureProps.normalMap.wrapS =
    nineTextureProps.normalMap.wrapT =
    nineTextureProps.roughnessMap.wrapS =
    nineTextureProps.roughnessMap.wrapT =
    nineTextureProps.aoMap.wrapS =
    nineTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;



  const tenTextureProps = useTexture({
    map: './gcdTextures/texTen/blue.jpg',
    // displacementMap: './textures/Catacomb_Wall_001_height.png',
    normalMap: './gcdTextures/texTen/blue.jpg',
    roughnessMap: './gcdTextures/texTen/blue.jpg',
    aoMap: './gcdTextures/texTen/blue.jpg',
  })

  tenTextureProps.map.repeat.set(3, 3);
  tenTextureProps.normalMap.repeat.set(3, 3);
  tenTextureProps.roughnessMap.repeat.set(3, 3);
  tenTextureProps.aoMap.repeat.set(3, 3);

  tenTextureProps.map.wrapS =
    tenTextureProps.map.wrapT =
    tenTextureProps.normalMap.wrapS =
    tenTextureProps.normalMap.wrapT =
    tenTextureProps.roughnessMap.wrapS =
    tenTextureProps.roughnessMap.wrapT =
    tenTextureProps.aoMap.wrapS =
    tenTextureProps.aoMap.wrapT =
    THREE.RepeatWrapping;


  console.log(lawnPillarDrapeOne, lpdOneTexture);

  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Scene">

        {lawnPillarDrapeOne === true && (
          <>
            <group name='scene1' visible={true}>
              <group name="gpd1012" position={[-2.03, -1.76, 3.43]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1012_1" geometry={nodes.gpd1012_1.geometry} material={materials['curtainnn.012']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1012_2" geometry={nodes.gpd1012_2.geometry} material={materials['da.012']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1013" position={[-5.51, -1.76, 1.8]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1013_1" geometry={nodes.gpd1013_1.geometry} material={materials['curtainnn.013']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1013_2" geometry={nodes.gpd1013_2.geometry} material={materials['da.013']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1014" position={[-8.08, -1.76, 0.56]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1014_1" geometry={nodes.gpd1014_1.geometry} material={materials['curtainnn.014']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1014_2" geometry={nodes.gpd1014_2.geometry} material={materials['da.014']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1015" position={[-10.73, -1.76, -0.69]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1015_1" geometry={nodes.gpd1015_1.geometry} material={materials['curtainnn.015']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1015_2" geometry={nodes.gpd1015_2.geometry} material={materials['da.015']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1016" position={[0.53, -1.76, 4.64]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1016_1" geometry={nodes.gpd1016_1.geometry} material={materials['curtainnn.016']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1016_2" geometry={nodes.gpd1016_2.geometry} material={materials['da.016']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1017" position={[3.08, -1.76, 5.85]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.52}>
                <mesh name="gpd1017_1" geometry={nodes.gpd1017_1.geometry} material={materials['curtainnn.017']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1017_2" geometry={nodes.gpd1017_2.geometry} material={materials['da.017']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1018" position={[10.22, -1.76, -8.89]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1018_1" geometry={nodes.gpd1018_1.geometry} material={materials['curtainnn.018']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1018_2" geometry={nodes.gpd1018_2.geometry} material={materials['da.018']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1019" position={[7.63, -1.76, -10.1]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1019_1" geometry={nodes.gpd1019_1.geometry} material={materials['curtainnn.019']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1019_2" geometry={nodes.gpd1019_2.geometry} material={materials['da.019']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1020" position={[4.96, -1.76, -11.38]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1020_1" geometry={nodes.gpd1020_1.geometry} material={materials['curtainnn.020']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1020_2" geometry={nodes.gpd1020_2.geometry} material={materials['da.020']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1021" position={[1.9, -1.76, -12.84]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1021_1" geometry={nodes.gpd1021_1.geometry} material={materials['curtainnn.021']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1021_2" geometry={nodes.gpd1021_2.geometry} material={materials['da.021']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1022" position={[-0.74, -1.76, -14.11]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1022_1" geometry={nodes.gpd1022_1.geometry} material={materials['curtainnn.022']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1022_2" geometry={nodes.gpd1022_2.geometry} material={materials['da.022']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1023" position={[-3.36, -1.76, -15.29]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1023_1" geometry={nodes.gpd1023_1.geometry} material={materials['curtainnn.023']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1023_2" geometry={nodes.gpd1023_2.geometry} material={materials['da.023']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1024" position={[-5.95, -1.76, -16.58]} rotation={[Math.PI / 2, 0, 0.44]} scale={[0.52, 0.52, 0.39]}>
                <mesh name="gpd1024_1" geometry={nodes.gpd1024_1.geometry} material={materials['curtainnn.024']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1024_2" geometry={nodes.gpd1024_2.geometry} material={materials['da.024']} >
                  <meshStandardMaterial {...lpdOneTexture === 0 ? materialTextureProps
                    : lpdOneTexture === 1 ? gcdRedTextureProps
                      : lpdOneTexture === 2 ? gcdYellowTextureProps
                        : lpdOneTexture === 3 ? fourTextureProps
                          : lpdOneTexture === 4 ? fiveTextureProps
                            : lpdOneTexture === 5 ? sixTextureProps
                              : lpdOneTexture === 6 ? sevenTextureProps
                                : lpdOneTexture === 7 ? eightTextureProps
                                  : lpdOneTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>

            </group>

          </>
        )}


        {lawnPillarDrapeTwo === true && (
          <>

            <group name='scene2' visible={true}>

              <group name="gpd1037" position={[-10.62, -0.39, -0.67]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1037_1" geometry={nodes.gpd1037_1.geometry} material={materials['curtainnn.037']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1037_2" geometry={nodes.gpd1037_2.geometry} material={materials['da.037']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1038" position={[-8.02, -0.39, 0.53]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1038_1" geometry={nodes.gpd1038_1.geometry} material={materials['curtainnn.038']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1038_2" geometry={nodes.gpd1038_2.geometry} material={materials['da.038']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1039" position={[-5.43, -0.39, 1.79]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1039_1" geometry={nodes.gpd1039_1.geometry} material={materials['curtainnn.039']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1039_2" geometry={nodes.gpd1039_2.geometry} material={materials['da.039']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1040" position={[-1.94, -0.39, 3.38]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1040_1" geometry={nodes.gpd1040_1.geometry} material={materials['curtainnn.040']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1040_2" geometry={nodes.gpd1040_2.geometry} material={materials['da.040']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1041" position={[0.65, -0.39, 4.62]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1041_1" geometry={nodes.gpd1041_1.geometry} material={materials['curtainnn.041']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1041_2" geometry={nodes.gpd1041_2.geometry} material={materials['da.041']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1042" position={[3.22, -0.39, 5.83]} rotation={[Math.PI / 2, 0, -2.67]} scale={[0.65, 0.67, 0.77]}>
                <mesh name="gpd1042_1" geometry={nodes.gpd1042_1.geometry} material={materials['curtainnn.042']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1042_2" geometry={nodes.gpd1042_2.geometry} material={materials['da.042']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1043" position={[10.06, -0.74, -8.87]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1043_1" geometry={nodes.gpd1043_1.geometry} material={materials['curtainnn.043']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1043_2" geometry={nodes.gpd1043_2.geometry} material={materials['da.043']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1044" position={[7.54, -0.75, -10.11]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1044_1" geometry={nodes.gpd1044_1.geometry} material={materials['curtainnn.044']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1044_2" geometry={nodes.gpd1044_2.geometry} material={materials['da.044']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1045" position={[4.93, -0.75, -11.36]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1045_1" geometry={nodes.gpd1045_1.geometry} material={materials['curtainnn.045']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1045_2" geometry={nodes.gpd1045_2.geometry} material={materials['da.045']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1046" position={[1.81, -0.75, -12.82]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1046_1" geometry={nodes.gpd1046_1.geometry} material={materials['curtainnn.046']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1046_2" geometry={nodes.gpd1046_2.geometry} material={materials['da.046']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1047" position={[-0.82, -0.75, -14.03]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1047_1" geometry={nodes.gpd1047_1.geometry} material={materials['curtainnn.047']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1047_2" geometry={nodes.gpd1047_2.geometry} material={materials['da.047']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
              <group name="gpd1048" position={[-3.42, -0.75, -15.29]} rotation={[Math.PI / 2, 0, 0.47]} scale={[0.65, 0.67, 0.57]}>
                <mesh name="gpd1048_1" geometry={nodes.gpd1048_1.geometry} material={materials['curtainnn.048']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
                <mesh name="gpd1048_2" geometry={nodes.gpd1048_2.geometry} material={materials['da.048']} >
                  <meshStandardMaterial {...lpdTwoTexture === 0 ? materialTextureProps
                    : lpdTwoTexture === 1 ? gcdRedTextureProps
                      : lpdTwoTexture === 2 ? gcdYellowTextureProps
                        : lpdTwoTexture === 3 ? fourTextureProps
                          : lpdTwoTexture === 4 ? fiveTextureProps
                            : lpdTwoTexture === 5 ? sixTextureProps
                              : lpdTwoTexture === 6 ? sevenTextureProps
                                : lpdTwoTexture === 7 ? eightTextureProps
                                  : lpdTwoTexture === 8 ? nineTextureProps
                                    : tenTextureProps} />
                </mesh>
              </group>
            </group>

          </>
        )}

      </group>
    </group >
  )
}

useGLTF.preload('./models/lawn/lpd.gltf')
