/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/test.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function TestFlowers(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/testFlowers.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[0.3, 0.3, 0.3]} visible={false} >
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[-14.58, 0.51, -11.56]} rotation={[0, -0.45, -Math.PI / 2]} scale={[2.14, 4.57, 2.9]} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.002']} position={[-11.73, 2.54, -10.24]} scale={1.07} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.83, 1.8, 4.48]} rotation={[0, -0.44, -Math.PI / 2]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Material} position={[8.29, 0.86, -9.9]} rotation={[0, -0.44, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/testFlowers.gltf')
